name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo código
        uses: actions/checkout@v5
      - name: Setup do Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: nstall dependecies
        working-directory: ./src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execução dos testes
        working-directory: ./src
        run: |
          python -m pytest tests/ -v   



      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            docker.io/car21/encontros-tech:latest
            docker.io/car21/encontros-tech:${{ github.run_number }}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - run: echo "Obter Código"
      - run: echo "configurar o kubeconfig"
      - run: echo "executar o apply"
